version: '2'

services:
  
  odoo_server:
    # NOTE - delete "docker.uclv.cu/" to download image from docker hub
    image: docker.uclv.cu/odoo:14.0
    depends_on:
      - database
    ports:
      - "8069:8069"
    environment:
      - HOST=database
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-server:/var/lib/odoo
      # - ./code/config:/etc/odoo
      - ./code/addons:/mnt/extra-addons

  database:
    # NOTE - delete "docker.uclv.cu/" to download image from docker hub
    image: docker.uclv.cu/postgres:13.2-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-database:/var/lib/postgresql/data/pgdata

volumes:
  odoo-server:
  odoo-database: